#!/usr/bin/env python3
"""
Python API Examples for Tongyi Agent

This file demonstrates various ways to use Tongyi Agent programmatically
in Python applications.
"""

import os
import sys
from pathlib import Path

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))


def example_1_basic_usage():
    """Example 1: Basic usage with Tongyi Orchestrator"""
    print("\n" + "="*60)
    print("Example 1: Basic Usage")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        # Create orchestrator with default settings
        orch = TongyiOrchestrator(root=".")

        # Ask a simple question
        answer = orch.run("What is the purpose of this project?")
        print(f"Answer: {answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_2_with_custom_root():
    """Example 2: Analyzing a specific directory"""
    print("\n" + "="*60)
    print("Example 2: Analyzing Specific Directory")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        # Analyze a specific directory
        orch = TongyiOrchestrator(root="./src")

        # Ask about the code in that directory
        answer = orch.run("What files are in this directory?")
        print(f"Directory contents:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_3_code_analysis():
    """Example 3: Analyzing code"""
    print("\n" + "="*60)
    print("Example 3: Code Analysis")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Analyze a specific file
        answer = orch.run(
            "Analyze src/cli.py for potential issues "
            "and suggest improvements"
        )
        print(f"Analysis:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_4_file_search():
    """Example 4: Searching for specific code patterns"""
    print("\n" + "="*60)
    print("Example 4: Code Pattern Search")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Search for specific patterns
        answer = orch.run(
            "Find all functions that handle API calls "
            "in the codebase"
        )
        print(f"Found:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_5_documentation_generation():
    """Example 5: Generating documentation"""
    print("\n" + "="*60)
    print("Example 5: Documentation Generation")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Generate documentation for a module
        answer = orch.run(
            "Generate API documentation for the "
            "tongyi_orchestrator module with examples"
        )
        print(f"Documentation:\n{answer}")

        # Save to file
        with open("tongyi_orchestrator_docs.md", "w") as f:
            f.write(answer)
        print("\n✅ Documentation saved to tongyi_orchestrator_docs.md")

    except Exception as e:
        print(f"Error: {e}")


def example_6_test_generation():
    """Example 6: Generating test cases"""
    print("\n" + "="*60)
    print("Example 6: Test Case Generation")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Generate tests for a specific file
        answer = orch.run(
            "Generate comprehensive pytest test cases "
            "for src/sandbox_exec.py including edge cases"
        )
        print(f"Generated tests:\n{answer}")

        # Save to test file
        with open("test_sandbox_autogenerated.py", "w") as f:
            f.write(answer)
        print("\n✅ Tests saved to test_sandbox_autogenerated.py")

    except Exception as e:
        print(f"Error: {e}")


def example_7_error_analysis():
    """Example 7: Analyzing errors and suggesting fixes"""
    print("\n" + "="*60)
    print("Example 7: Error Analysis")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Provide an error and ask for analysis
        error_message = """
        ImportError: cannot import name 'TongyiOrchestrator'
        from 'tongyi_orchestrator'
        """

        answer = orch.run(
            f"Analyze this error and suggest fixes:\n{error_message}"
        )
        print(f"Analysis:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_8_batch_analysis():
    """Example 8: Analyzing multiple files"""
    print("\n" + "="*60)
    print("Example 8: Batch File Analysis")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # List of files to analyze
        files_to_analyze = [
            "src/cli.py",
            "src/sandbox_exec.py",
            "src/code_search.py"
        ]

        print(f"Analyzing {len(files_to_analyze)} files...\n")

        results = []
        for file_path in files_to_analyze:
            if os.path.exists(file_path):
                answer = orch.run(
                    f"Analyze {file_path} for security issues"
                )
                results.append((file_path, answer))
                print(f"✅ {file_path}")
            else:
                print(f"⚠️  {file_path} not found")

        # Print summary
        print("\n" + "="*60)
        print("Summary:")
        print("="*60)
        for file_path, analysis in results:
            print(f"\n{file_path}:")
            print(analysis[:200] + "..." if len(analysis) > 200 else analysis)

    except Exception as e:
        print(f"Error: {e}")


def example_9_configuration():
    """Example 9: Custom configuration"""
    print("\n" + "="*60)
    print("Example 9: Custom Configuration")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        # Create orchestrator with custom root
        orch = TongyiOrchestrator(root="./src")

        # You can also pass custom parameters if needed
        answer = orch.run(
            "What is the architecture of this codebase?"
        )
        print(f"Architecture overview:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def example_10_concurrent_queries():
    """Example 10: Running multiple queries in sequence"""
    print("\n" + "="*60)
    print("Example 10: Multiple Queries")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        queries = [
            "List all Python files in src/",
            "What is the main entry point?",
            "How is configuration managed?",
            "Describe the tool registry"
        ]

        results = []
        for i, query in enumerate(queries, 1):
            print(f"\nQuery {i}/{len(queries)}: {query}")
            answer = orch.run(query)
            results.append(answer)
            print(f"✅ Completed")

        print("\n" + "="*60)
        print("All Results:")
        print("="*60)
        for i, (query, answer) in enumerate(zip(queries, results), 1):
            print(f"\n{i}. {query}")
            print(f"   {answer[:150]}...")

    except Exception as e:
        print(f"Error: {e}")


def example_11_with_claude_sdk():
    """Example 11: Using Claude Agent SDK orchestrator"""
    print("\n" + "="*60)
    print("Example 11: Claude Agent SDK Integration")
    print("="*60)

    try:
        from claude_agent_orchestrator import ClaudeAgentOrchestrator

        # Create Claude agent orchestrator
        orch = ClaudeAgentOrchestrator(root=".")

        # Ask a question using Claude
        answer = orch.run("What is the main purpose of this project?")
        print(f"Answer: {answer}")

    except ImportError:
        print("Claude Agent SDK not available. Install with:")
        print("pip install anthropic")
    except Exception as e:
        print(f"Error: {e}")


def example_12_tool_usage():
    """Example 12: Direct tool usage"""
    print("\n" + "="*60)
    print("Example 12: Direct Tool Usage")
    print("="*60)

    try:
        from tongyi_orchestrator import TongyiOrchestrator

        orch = TongyiOrchestrator(root=".")

        # Ask Tongyi to use specific tools
        answer = orch.run(
            "Use the search_code tool to find all uses of "
            "the verification gate"
        )
        print(f"Tool results:\n{answer}")

    except Exception as e:
        print(f"Error: {e}")


def main():
    """Run all examples"""
    print("\n" + "="*60)
    print("Tongyi Agent Python API Examples")
    print("="*60)
    print("\nNote: Some examples may require API keys and network access")
    print("Set OPENROUTER_API_KEY environment variable if needed\n")

    examples = [
        example_1_basic_usage,
        example_2_with_custom_root,
        example_3_code_analysis,
        example_4_file_search,
        example_5_documentation_generation,
        example_6_test_generation,
        example_7_error_analysis,
        example_8_batch_analysis,
        example_9_configuration,
        example_10_concurrent_queries,
        example_11_with_claude_sdk,
        example_12_tool_usage
    ]

    # Run all examples
    for example in examples:
        try:
            example()
        except Exception as e:
            print(f"\n⚠️  Example failed: {e}")
        print("\n" + "-"*60 + "\n")

    print("\n✅ All examples completed!")


if __name__ == "__main__":
    # Check for API key
    if not os.getenv("OPENROUTER_API_KEY"):
        print("⚠️  Warning: OPENROUTER_API_KEY not set")
        print("Some examples may not work without an API key\n")

    main()
